experiment_name: spock_survival_SMC_4
inputs_folder: './input_files/input_files_two_species_spock_manu_2/input_files/'
output_folder: './output/'

# Start time, end time, time interval
t_0: 0
t_end: 1500
dt: 0.5

final_epsilon: 
  - 1e-9
fit_species:
  - 0
  - 1

population_size: 6000
n_sims_batch: 200


## Distance options
# 0: stable steady state
# 1: oscillations
# 2: survival
distance_function_mode: 2

# Choose which algorithm to run
run_rejection: Y
run_SMC: N