experiment_name: BK_manu_three_species_rej_3
inputs_folder: './input_files/input_files_one_species_1/input_files/'
output_folder: './output/'

# Start time, end time, time interval
t_0: 0
t_end: 15
dt: 0.1

final_epsilon: 
  - 1e-9
  - 0.001
  - 1000

fit_species:
  - 0

abs_tol: 1e-15
rel_tol: 1e-5

population_size: 10
n_sims_batch: 10

## Distance options
# 0: stable steady state
# 1: oscillations
# 2: survival
distance_function_mode: 0

# Choose which algorithm to run
run_rejection: Y
run_SMC: N

alpha: 0.5