experiment_name: BK_manu_three_species_rej_3
inputs_folder: './input_files/input_files_three_species_6/input_files/'
output_folder: './output/'

# Start time, end time, time interval
t_0: 0
t_end: 1000
dt: 0.5

final_epsilon: 
  - 1e-9
  - 0.001
  - 1000

fit_species:
  - 0
  - 1
  - 2

abs_tol: 1e-15
rel_tol: 1e-5

population_size: 50000
n_sims_batch: 5000

## Distance options
# 0: stable steady state
# 1: oscillations
# 2: survival
distance_function_mode: 0

# Choose which algorithm to run
run_rejection: N
run_SMC: Y

alpha: 0.5